import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body  className = 'w-full max-w-screen-xl overflow-auto mx-auto'>
        <header className = 'sticky top-0 bg-white z-10 border-b'>
          <Navbar></Navbar>
        </header>
        {children}  
      </body>
    </html>
  );
}
