name: hotels-CI  

on: [pull_request]  

jobs:
  build:                    
    name: Lint
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v3       
      - name : Set up node 20       
        uses: actions/setup-node@v2                           
        with:
          node-version: '20' 
      - run: npm install

      - run: CI='false' npm run build
        env: 
          GOOGLE_OAUTH_ID : ${{secrets.NEXT_PUBLIC_GOOGLE_OAUTH_ID}}
          GOOGLE_OAUTH_SECRET : ${{secrets.NEXT_PUBLIC_GOOGLE_OAUTH_SECRET}}
          NEXTAUTH_SECRET : ${{secrets.NEXTAUTH_SECRET}}
          SANITY_PROJECT_ID : ${{secrets.NEXT_PUBLIC_SANITY_PROJECT_ID}}
          SANITY_DATASET : ${{secrets.NEXT_PUBLIC_SANITY_DATASET}}
          SANITY_SECRET_TOKEN : ${{secrets.NEXT_PUBLIC_SANITY_SECRET_TOKEN}}